name: Book-Cover
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/Book-Cover
  original_url: https://huggingface.co/spaces/Chris4K/Book-Cover

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
